name = "Birb"
author = "sollmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0569ec7d59c1864d07b958f930a1ba2a7cd6fc9b5fc8f4f9f36df9a282042cb4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
