name = "Birb"
author = "sollmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "999b494f0a53c039e0dafcddc4813aeabe1fad1d5f644e6944ae5068701454a3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
