name = "Birb"
author = "sollmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "085f8933c070c79d3606ac44869eb4428ad12bf27d5862a1c9cfa5136d5a0e7f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
