name = "Birb"
author = "sollmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f152cf4b67521bbb94abfe490973b4e78c5cc7788dbbe425e00bac0243a9415"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
