#Disables some useful yet mostly unnoticeable features that may improve mod compatibility in rare cases
compatibilityMode = false
#Style of the accessory inventory button
#DEFAULT: The normal Ohmega button style
#LEGACY: A curios/baubles inspired button that renders next to the inventory player model
#TAG: A small tag-like button appearing just off the top corner of the inventory
#HIDDEN: Will not show, use the dedicated keybind to open the accessory inventory instead
#Allowed Values: DEFAULT, LEGACY, TAG, HIDDEN
buttonStyle = "DEFAULT"
#The side of the inventory that the accessory inventory will be placed
#Allowed Values: LEFT, RIGHT
inventorySide = "RIGHT"
#If true, will display a tooltip box of the type of accessory slot when it is hovered over
showHoverTooltip = true
#The maximum columns to render
# Default: 1
# Range: 1 ~ 4
maxColumns = 1
#The maximum amount of slots per column
#If exceeded, a new column will be made if it does not exceed "maxColumns"
# Default: 8
# Range: 1 ~ 32
maxColumnSlots = 8
#The maximum amount of slots to render per column
# Default: 6
# Range: 1 ~ 6
maxColumnRenderSlots = 6
